package virtualpiano;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Sayed
 */
public class PianoFrame extends javax.swing.JFrame {
    public PianoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ds1Button = new javax.swing.JButton();
        CsButton = new javax.swing.JButton();
        DsButton = new javax.swing.JButton();
        FsButton = new javax.swing.JButton();
        GsButton = new javax.swing.JButton();
        BbButton = new javax.swing.JButton();
        Cs1Button = new javax.swing.JButton();
        F1Button = new javax.swing.JButton();
        CButton = new javax.swing.JButton();
        DButton = new javax.swing.JButton();
        EButton = new javax.swing.JButton();
        FButton = new javax.swing.JButton();
        GButton = new javax.swing.JButton();
        AButton = new javax.swing.JButton();
        BButton = new javax.swing.JButton();
        C1Button = new javax.swing.JButton();
        D1Button = new javax.swing.JButton();
        E1Button = new javax.swing.JButton();
        soft = new javax.swing.JCheckBox();
        metal = new javax.swing.JCheckBox();
        SoundType = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KeyBoard = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.lightGray);
        getContentPane().setLayout(null);

        Ds1Button.setBackground(java.awt.Color.black);
        Ds1Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ds1Button.setForeground(java.awt.Color.white);
        Ds1Button.setText("D#1");
        Ds1Button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Ds1Button.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Ds1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ds1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Ds1Button);
        Ds1Button.setBounds(710, 160, 50, 220);

        CsButton.setBackground(java.awt.Color.black);
        CsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CsButton.setForeground(java.awt.Color.white);
        CsButton.setText("C#");
        CsButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CsButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CsButton);
        CsButton.setBounds(150, 160, 50, 220);

        DsButton.setBackground(java.awt.Color.black);
        DsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DsButton.setForeground(java.awt.Color.white);
        DsButton.setText("D#");
        DsButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DsButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DsButton);
        DsButton.setBounds(220, 160, 50, 220);

        FsButton.setBackground(java.awt.Color.black);
        FsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FsButton.setForeground(java.awt.Color.white);
        FsButton.setText("F#");
        FsButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        FsButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        FsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FsButton);
        FsButton.setBounds(360, 160, 50, 220);

        GsButton.setBackground(java.awt.Color.black);
        GsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GsButton.setForeground(java.awt.Color.white);
        GsButton.setText("G#");
        GsButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        GsButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GsButton);
        GsButton.setBounds(430, 160, 50, 220);

        BbButton.setBackground(java.awt.Color.black);
        BbButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BbButton.setForeground(java.awt.Color.white);
        BbButton.setText("Bb");
        BbButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BbButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BbButton);
        BbButton.setBounds(500, 160, 50, 220);

        Cs1Button.setBackground(java.awt.Color.black);
        Cs1Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cs1Button.setForeground(java.awt.Color.white);
        Cs1Button.setText("C#1");
        Cs1Button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Cs1Button.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Cs1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cs1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Cs1Button);
        Cs1Button.setBounds(640, 160, 50, 220);

        F1Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        F1Button.setForeground(java.awt.Color.gray);
        F1Button.setText("F1");
        F1Button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        F1Button.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        F1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(F1Button);
        F1Button.setBounds(810, 160, 70, 329);

        CButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CButton.setForeground(java.awt.Color.gray);
        CButton.setText("C");
        CButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CButton);
        CButton.setBounds(110, 160, 70, 329);

        DButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DButton.setForeground(java.awt.Color.gray);
        DButton.setText("D");
        DButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DButton);
        DButton.setBounds(180, 160, 70, 329);

        EButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EButton.setForeground(java.awt.Color.gray);
        EButton.setText("E");
        EButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        EButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EButton);
        EButton.setBounds(250, 160, 70, 329);

        FButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        FButton.setForeground(java.awt.Color.gray);
        FButton.setText("F");
        FButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        FButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        FButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FButton);
        FButton.setBounds(320, 160, 70, 329);

        GButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        GButton.setForeground(java.awt.Color.gray);
        GButton.setText("G");
        GButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        GButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GButton);
        GButton.setBounds(390, 160, 70, 329);

        AButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AButton.setForeground(java.awt.Color.gray);
        AButton.setText("A");
        AButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        AButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AButton);
        AButton.setBounds(460, 160, 70, 329);

        BButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BButton.setForeground(java.awt.Color.gray);
        BButton.setText("B");
        BButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BButton);
        BButton.setBounds(530, 160, 70, 329);

        C1Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        C1Button.setForeground(java.awt.Color.gray);
        C1Button.setText("C1");
        C1Button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        C1Button.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        C1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(C1Button);
        C1Button.setBounds(600, 160, 70, 329);

        D1Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        D1Button.setForeground(java.awt.Color.gray);
        D1Button.setText("D1");
        D1Button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        D1Button.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        D1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(D1Button);
        D1Button.setBounds(670, 160, 70, 329);

        E1Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        E1Button.setForeground(java.awt.Color.gray);
        E1Button.setText("E1");
        E1Button.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        E1Button.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        E1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(E1Button);
        E1Button.setBounds(740, 160, 70, 329);

        soft.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soft.setText("Soft Piano");
        soft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softActionPerformed(evt);
            }
        });
        getContentPane().add(soft);
        soft.setBounds(110, 70, 109, 31);

        metal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        metal.setText("Metal Drum");
        getContentPane().add(metal);
        metal.setBounds(110, 110, 140, 40);

        SoundType.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SoundType.setText("Sounds");
        getContentPane().add(SoundType);
        SoundType.setBounds(110, 20, 90, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Play using:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(790, 30, 150, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Virtual Piano");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 50, 360, 90);

        KeyBoard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        KeyBoard.setText("KeyBoard");
        KeyBoard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyBoardKeyPressed(evt);
            }
        });
        getContentPane().add(KeyBoard);
        KeyBoard.setBounds(790, 70, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpiano/DSC100039699.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1, -4, 1030, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ButtonActionPerformed
        if(soft.isSelected()){
               String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\F1.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\F1_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_F1ButtonActionPerformed

    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonActionPerformed
        if(soft.isSelected()){
               String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\C.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\C_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_CButtonActionPerformed

    private void DButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DButtonActionPerformed
        if(soft.isSelected()){
               String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\D.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\D_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_DButtonActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        if(soft.isSelected()){
               String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\E.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\E_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_EButtonActionPerformed

    private void FButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FButtonActionPerformed
        if(soft.isSelected()){
               String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\F.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="C:\\Users\\Sayed\\Documents\\NetBeansProjects\\VirtualPiano\\src\\AudioFiles\\F_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_FButtonActionPerformed

    private void GButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\G.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\G_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_GButtonActionPerformed

    private void AButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\A.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\A_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_AButtonActionPerformed

    private void BButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\B.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\B_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_BButtonActionPerformed

    private void C1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\C1.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\C1_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_C1ButtonActionPerformed

    private void D1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ButtonActionPerformed
       if(soft.isSelected()){
               String path ="src\\AudioFiles\\D1.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\D1_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_D1ButtonActionPerformed

    private void E1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\E1.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\E1_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_E1ButtonActionPerformed

    private void softActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_softActionPerformed

    private void KeyBoardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyBoardKeyPressed
          if(metal.isSelected()){
            soft.setSelected(false);
        }
        if(KeyBoard.isSelected()){
            int X=evt.getKeyCode();
                 if(X==KeyEvent.VK_A){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\C.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\C_Drum.wav";
                playsound(path);   
           }
        }
                 if(X==KeyEvent.VK_S){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\D.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\D_Drum.wav";
                playsound(path);   
           }
        }
                 if(X==KeyEvent.VK_D){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\E.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\E_Drum.wav";
                playsound(path);   
           }
        }
                 if(X==KeyEvent.VK_F){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\F.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\F_Drum.wav";
                playsound(path);   
           }
        }
                 if(X==KeyEvent.VK_G){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\G.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\G_Drum.wav";
                playsound(path);   
           }
        }
                 if(X==KeyEvent.VK_H){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\A.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\A_Drum.wav";
                playsound(path);   
           }
        }
                 if(X==KeyEvent.VK_J){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\B.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\B_Drum.wav";
                playsound(path);   
           }
        }
                 if(X==KeyEvent.VK_K){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\C1.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\C1_Drum.wav";
                playsound(path);   
           }
        }
                 if(X==KeyEvent.VK_L){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\D1.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\D1_Drum.wav";
                playsound(path);   
           }
        }
              if(X==KeyEvent.VK_SEMICOLON){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\E1.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\E1_Drum.wav";
                playsound(path);   
           }
        }if(X==KeyEvent.VK_QUOTE){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\F1.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\F1_Drum.wav";
                playsound(path);   
           }
        }
        if(X==KeyEvent.VK_W){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\Cs.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\Cs1_Drum.wav";
                playsound(path);   
           }
        }
        if(X==KeyEvent.VK_E){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\Ds.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\Ds_Drum.wav";
                playsound(path);   
           }
        }
        if(X==KeyEvent.VK_T){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\Fs.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\Fs_Drum.wav";
                playsound(path);   
           }
        }
        if(X==KeyEvent.VK_Y){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\Gs.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\Gs_Drum.wav";
                playsound(path);   
           }
        }
        if(X==KeyEvent.VK_U){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\Bb.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\Bb_Drum.wav";
                playsound(path);   
           }
        }
        if(X==KeyEvent.VK_O){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\Cs1.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\CS1_Drum.wav";
                playsound(path);   
           }
        }
        if(X==KeyEvent.VK_P){
             if(soft.isSelected()){
                 metal.setSelected(false);
                String path="src\\AudioFiles\\Ds1.wav";
                playsound(path);
       }
            if(metal.isSelected()){
               String path = "src\\AudioFiles\\Ds1_Drum.wav";
                playsound(path);   
           }
        }
        }
    }//GEN-LAST:event_KeyBoardKeyPressed

    private void CsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CsButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\Cs.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\Cs_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_CsButtonActionPerformed

    private void DsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DsButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\Ds.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\Ds_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_DsButtonActionPerformed

    private void FsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FsButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\Fs.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\Fs_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_FsButtonActionPerformed

    private void GsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GsButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\Gs.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\Gs_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_GsButtonActionPerformed

    private void BbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\Bb.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\Bb_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_BbButtonActionPerformed

    private void Cs1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cs1ButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\Cs1.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\Cs1_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_Cs1ButtonActionPerformed

    private void Ds1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ds1ButtonActionPerformed
        if(soft.isSelected()){
               String path ="src\\AudioFiles\\Ds1.wav";
               playsound(path);
                }
            if(metal.isSelected()){
                soft.setSelected(false);
         String path ="src\\AudioFiles\\Ds1_Drum.wav";
               playsound(path);
                }
    }//GEN-LAST:event_Ds1ButtonActionPerformed
        void playsound(String path){
        try{
            File file = new File(path);
            InputStream Audio = new FileInputStream(path);
            AudioStream music =new AudioStream(Audio);
            AudioPlayer.player.start(music);
    }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }}
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PianoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PianoFrame frame = new PianoFrame();
                frame.setVisible(true);
                frame.setSize(1028, 580);
                frame.setResizable(false);
                frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AButton;
    private javax.swing.JButton BButton;
    private javax.swing.JButton BbButton;
    private javax.swing.JButton C1Button;
    private javax.swing.JButton CButton;
    private javax.swing.JButton Cs1Button;
    private javax.swing.JButton CsButton;
    private javax.swing.JButton D1Button;
    private javax.swing.JButton DButton;
    private javax.swing.JButton Ds1Button;
    private javax.swing.JButton DsButton;
    private javax.swing.JButton E1Button;
    private javax.swing.JButton EButton;
    private javax.swing.JButton F1Button;
    private javax.swing.JButton FButton;
    private javax.swing.JButton FsButton;
    private javax.swing.JButton GButton;
    private javax.swing.JButton GsButton;
    private javax.swing.JCheckBox KeyBoard;
    private javax.swing.JLabel SoundType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox metal;
    private javax.swing.JCheckBox soft;
    // End of variables declaration//GEN-END:variables
}
